chdir: /usr/local/vtmena-is/current
port: "9000"
log: log/thin.log
max_conns: 1024
timeout: 30
environment: production
max_persistent_conns: 512
daemonize: true
address: 0.0.0.0
pid_file: log/thin.pid
servers: 2